#!/usr/bin/env bash
# SJL Sovereign Cloud — LLM Skill Export Script
# Generates LLM-specific instruction files from the canonical Claude Code skill.
# Source: .claude/commands/sjl-file-governance.md
# Run from the repository root.
# Idempotent — safe to re-run after updates to the source skill.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="${REPO_ROOT}/.claude/commands/sjl-file-governance.md"

if [[ ! -f "$SOURCE" ]]; then
  echo "ERROR: source skill not found at $SOURCE" >&2
  exit 1
fi

# Strip the Claude-specific header lines (first 4 lines) to get clean body
SKILL_BODY="$(tail -n +5 "$SOURCE")"

# ------------------------------------------------------------------
# Helper: write a file and report
# ------------------------------------------------------------------
write_file() {
  local dest="$1"
  local content="$2"
  mkdir -p "$(dirname "$dest")"
  printf '%s\n' "$content" > "$dest"
  echo "  wrote: ${dest#"$REPO_ROOT/"}"
}

echo "SJL Governance Skill Export"
echo "Source: ${SOURCE#"$REPO_ROOT/"}"
echo ""

# ------------------------------------------------------------------
# 1. GitHub Copilot  (.github/copilot-instructions.md)
# ------------------------------------------------------------------
write_file "${REPO_ROOT}/.github/copilot-instructions.md" "$(cat <<COPILOT
<!-- SJL Sovereign Cloud — File Governance Rules for GitHub Copilot -->
<!-- Auto-generated by export-skill-to-llms.sh — edit source at .claude/commands/sjl-file-governance.md -->

${SKILL_BODY}
COPILOT
)"

# ------------------------------------------------------------------
# 2. OpenAI Codex CLI  (AGENTS.md)
# ------------------------------------------------------------------
write_file "${REPO_ROOT}/AGENTS.md" "$(cat <<AGENTS
<!-- SJL Sovereign Cloud — File Governance Rules for OpenAI Codex CLI / AGENTS -->
<!-- Auto-generated by export-skill-to-llms.sh — edit source at .claude/commands/sjl-file-governance.md -->

${SKILL_BODY}
AGENTS
)"

# ------------------------------------------------------------------
# 3. Cursor IDE  (.cursor/rules/sjl-file-governance.mdc)
# ------------------------------------------------------------------
write_file "${REPO_ROOT}/.cursor/rules/sjl-file-governance.mdc" "$(cat <<CURSOR
---
description: SJL Sovereign Cloud file governance doctrine — naming, versioning, PARA, pipeline, change gates
globs: ["**/*"]
alwaysApply: true
---

<!-- Auto-generated by export-skill-to-llms.sh — edit source at .claude/commands/sjl-file-governance.md -->

${SKILL_BODY}
CURSOR
)"

# ------------------------------------------------------------------
# 4. Windsurf  (.windsurfrules)
# ------------------------------------------------------------------
write_file "${REPO_ROOT}/.windsurfrules" "$(cat <<WINDSURF
# SJL Sovereign Cloud — File Governance Rules for Windsurf
# Auto-generated by export-skill-to-llms.sh — edit source at .claude/commands/sjl-file-governance.md

${SKILL_BODY}
WINDSURF
)"

# ------------------------------------------------------------------
# 5. Google Gemini CLI  (GEMINI.md)
# ------------------------------------------------------------------
write_file "${REPO_ROOT}/GEMINI.md" "$(cat <<GEMINI
<!-- SJL Sovereign Cloud — File Governance Rules for Google Gemini CLI -->
<!-- Auto-generated by export-skill-to-llms.sh — edit source at .claude/commands/sjl-file-governance.md -->

${SKILL_BODY}
GEMINI
)"

echo ""
echo "Export complete. Files written:"
echo "  .github/copilot-instructions.md  — GitHub Copilot"
echo "  AGENTS.md                         — OpenAI Codex CLI"
echo "  .cursor/rules/sjl-file-governance.mdc — Cursor IDE"
echo "  .windsurfrules                    — Windsurf"
echo "  GEMINI.md                         — Google Gemini CLI"
echo ""
echo "Commit these files to make the skill available to all LLM tools."
